LICENSE, README.rst, croud/config.py, croud/login.py, croud/printer.py, croud/server.py, croud/util.py, setup.py, tests/unit_tests/test_commands.py, tests/unit_tests/test_config.py, tests/unit_tests/test_server.py, tests/unit_tests/test_util.py
This adds CrateDB Cloud Login functionality to the subcommand `login`.
It will open a browser tab to start the authentication process using OAuth.
After successful authentication the session token gets stored in the
local app dir (OS platform specific) so that other commands (e.g. `me`) can
can use it to run a query.
```bash
(env) ☁  ~  croud login --env dev
==> Info: A browser tab has been launched for you to login.
==> Info: Login successful.
(env) ☁  ~  croud me -r eastus.azure --env dev
{
"email": "hoschi@crate.io",
"username": "Google_104209952803880732135",
"name": "Hoschi Galoschi"
}
```
=> Implement OAuth2 Login flow

croud/session.py, setup.py
This popped up because Python 3.6 on MacOSX comes with its own private copy of
OpenSSL 👎 . That means the trust certificates in the system are no longer used as
defaults by the Python ssl module.
To fix this it is necessary to to ship the `Certifi` lib that contains
a collection of root certificates of the Mozilla CA Bundle.
=> Fix SSL error: SSL certificate verify failed

README.rst
so when the package is uploaded to pypi and the readme is rendered the
links to DEVELOP and CONTRIBUTING still work
=> replace relative links in README with absolute URLs

croud/config.py
Give the local cround config r+w permissions only.
=> set config permissions to user r+w only

CHANGES.rst, croud/me.py
It was decided that for the time being the CLI should not return the name field of a user, as it may be empty; so I've removed it from the GraphQL query
=> Removed name field from gql query in me sub command

README.rst, croud/config.py, croud/logout.py, croud/me.py, croud/session.py, setup.py, tests/unit_tests/test_config.py, tests/unit_tests/test_session.py
If the config file that holds the login credentials has an
incompatible or incorrect format the user will be informed to remove the
config file.
```
==> Error: Incompatible storage format in /home/mibe/.config/Crate/croud.yaml. Please remove the config and try again.
```
=> Note the incompatible storage format of config across versions

croud/login.py
Running `croud login` without an env flag failed because there was no env set, and a function is called on the env variable before it is loaded from the auth context
=> Add check to make sure env variable cannot be None when logging in

croud/__main__.py, croud/cmd.py, tests/unit_tests/test_cmd.py
This fixes an issue that caused the `--version` argument to show a help
output instead of a version tag.
=> Fixed --help and --version argument on top level

croud/clusters/list.py, tests/unit_tests/test_commands.py
It's been decided that the hardware specs should not be included in the output when listing clusters
=> Removed hardware specs from list clusters command

DEVELOP.rst
Before uploading the package to the real PyPI index it is recommended to
upload it the test index first.
=> Added note to upload package on Test PyPI index first

tests/unit_tests/test_commands.py
The unit tests were referencing the same variable while testing commands (configuration class instance), so after running the login command, the auth context on the shared configuration class instance was updated. This PR fixes that by mocking the `set_context` method, and using a function to return default configuration settings for the mocked `load_config` return value
=> Fixed unit tests so that they do not interact with the same variable reference

CHANGES.rst, croud/login.py, tests/unit_tests/test_commands.py
This fixes a problem that occurred if `current_context: dev` the login has been opened on a prod environment instead of dev.
=> Fix: Login page needs to be picked according to the env set in current_context.

CHANGES.rst, croud/config.py, tests/unit_tests/test_config.py
PyYAML's `load()` does not guard against code execution. Let's use
`safe_load()`.
Ref https://nvd.nist.gov/vuln/detail/CVE-2017-18342
=> [SECURITY] Prevent arbitrary code execution when loading config file

CHANGES.rst, croud/__main__.py, croud/cmd.py
This just makes sure that when creating an organization only a valid plan type can be selected. I also removed the region arg from the `me` command because it doesn't do anything
=> Added fixed choices for plan-type arg and removed region arg from me command

CHANGES.rst, croud/config.py
Running ``croud config get output-fmt`` was returning an error because the key in settings uses an underscore, not a hyphen. This PR replaces hyphens with underscores before attempting to read settings
=> Fixed config get output-fmt by formatting arg name

CHANGES.rst, croud/__main__.py, croud/cmd.py
This PR changes the help output from:
```
usage: croud [-h] {add,list} ...
Role sub commands
positional arguments:
{add,list}
optional arguments:
-h, --help  show this help message and exit
```
to:
```
Usage: croud users roles [-h] {add,list} ...
Available Commands:
add         Adds a role to a user.
list        Lists all available roles.
Optional Arguments:
-h, --help  Show this help message and exit.
```
=> Reformatted help output

CHANGES.rst, croud/__main__.py, croud/cmd.py, croud/users/list.py, docs/docs/commands.txt, tests/unit_tests/test_commands.py
This adds the ``croud users list`` sub command, that allows users to list all users within organizations that they are part of. Super users are able to filter these by organization ID (``--org-id``), or list all users who are not part of any organization (``--no-org``)
=> Added users list sub command

croud/clusters/list.py, croud/gql.py, croud/me.py, croud/organizations/create.py, croud/organizations/list.py, croud/projects/list.py, croud/users/list.py, croud/users/roles/add.py, croud/users/roles/list.py, croud/users/roles/remove.py, tests/unit_tests/test_commands.py, tests/unit_tests/test_gql.py, tox.ini
During the initialisation of some tests in tests/unit_tests/test_commands.py (Tests which were mocking "Query") were raising exception. These tests were still passing because pytest just ignored the exceptions.
To resolve this we needed a function where the function call is in our hands, and for that we split the function call of print_result into two: one function for executing and one function for printing, meaning we can directly get access to the result.
=> fix broken query testing

CHANGES.rst, croud/__main__.py, croud/cmd.py, croud/projects/create.py, docs/docs/commands.txt, tests/unit_tests/test_commands.py
Implemented the `croud projects create` command with the arguments:
* name (required)
* organizationId (required)
+ implemented test for the `croud projects list` command
=> Implemented projects create command

croud/__main__.py
This adds the region argument back to ``projects create``. The reason for this is that Croud should provide the option to create a project in any region. If no ``--region`` option is provided, Croud will send the request to your default region (configured with ``config set --region REGION``). The mutation itself does not need a region input parameter because it will determine the project region via meta data (basically the subdomain (`<region>.cratedb[-dev].cloud`)). However, in Croud you should be able to override your default region, like you can when listing projects: ``croud projects list`` will list all projects in your default region, but this can be override so that you can check what your projects you have in other regions without changing your default region with ``config set …
=> Added the region arg back to creating projects

README.rst
because there was no hint about it.
=> linked CrateDB Cloud product page

CHANGES.rst, croud/__main__.py, croud/cmd.py, croud/organizations/users/commands.py, docs/docs/commands.txt, tests/unit_tests/test_commands.py
These two commands (``croud organiziations users add``, ``croud organizations users remove``) allow organization admins to add and remove users from organizations that they are admins for. Super users are able to add or remove any user from any organization
=> Added organizations users add and remove commands

docs/docs/commands.txt
This PR fixes unwanted whitespaces in option names caused by line breaks.
=> Fix layout of croud products deploy options in documentation

croud/__main__.py, croud/cmd.py, croud/exceptions.py, croud/gql.py, croud/organizations/users/commands.py, croud/session.py, tests/unit_tests/test_cmd.py, tests/unit_tests/test_commands.py, tests/unit_tests/test_gql.py, tests/unit_tests/test_session.py
This PR adds the support for sending GraphQL requests using variables which simplifies sending input arguments for mutations.
The PR contains of 3 commits:
- https://github.com/crate/croud/pull/82/commits/a32e0770ea0e2657da2b88fc3e7db6fe030d8fa6 : enhance testability of GraphQL client
- https://github.com/crate/croud/pull/82/commits/8cecccb1e1ce307b724b5014f8f4314cff9ea015 : introduce variables for GraphQL requests
- https://github.com/crate/croud/pull/82/commits/8326c46ed3a02dbd3c353cb589f2a6317e8dc7e4 : use variables for existing mutations that require input arguments
=> added graphql variables

tests/unit_tests/test_gql.py
the order or fixtures and parametrization is relevant for pytest to be
able to collect tests correctly
=> move gql client tests out of test class

croud/__main__.py, docs/docs/commands.txt
This will slightly improve the wording of some command descriptions in
the ``croud projects users`` argument namespace.
=> Improve the wording of some command descriptions

docs/docs/commands.txt
Also reordered the subcommands alphabetically.
=> Remove duplicate headline from consumer set docs

CHANGES.rst, croud/__main__.py, croud/organizations/users/commands.py, tests/unit_tests/test_commands.py
This PR makes it so that croud allows you to remove users from organizations via a user's email address or ID
=> Switch uid with user argment for removing users from organizations

tests/unit_tests/test_commands.py, tests/unit_tests/util/__init__.py
Updating the GraphQL queries to use variables instead of inline DSL will be addressed in a separate PR.
=> update command tests to use argument parsing

docs/docs/index.txt, docs/docs/user-roles.txt
Added "Roles" section in the docs with informations about the roles in CrateDB Cloud.
=> Added informations about roles to docs

croud/cmd.py, croud/config.py, croud/login.py, croud/logout.py, croud/session.py, tests/unit_tests/test_commands.py, tests/unit_tests/test_session.py
This adds a new environment to croud (local), which can be used for running croud against a local instance of cloud-app (via https://github.com/crate/cloud). As the configuration auth contexts have been appended to you will be logged out when using this new version as it will reformat your config file to support the local context.
=> Added local env

CHANGES.rst, croud/__main__.py, croud/clusters/commands.py, croud/cmd.py, docs/docs/commands.txt, setup.py, test-requirements.txt, tests/unit_tests/test_commands.py
This PR is should only be merged once the backend functionality is available in the cloud-app!
Added the command ``croud clusters deploy`` to enable users to deploy a new CrateDB cluster.
=> added "croud clusters deploy" command

CHANGES.rst, croud/__main__.py, croud/monitoring/grafana/commands.py, docs/docs/commands.txt, tests/unit_tests/test_commands.py, tests/unit_tests/util/__init__.py
This PR adds the commands ``monitoring grafana enable`` and ``monitoring grafana disable``, which are used to request that the cloud-app API enables or disables access to Grafana dashboards for a specified project.
=> Added enable and disable grafana commands

croud/parser.py, tests/unit_tests/test_parser.py, tests/unit_tests/util/__init__.py
A regression that caused the command help not showing required and
optional arguments correctly was introduced with commit #747f876
=> restore old formatting of command help

docs/conf.py, requirements-docs.txt
This commit fixes a regression that was introduced in version 0.5.73 of
the crate-docs-theme and was resolved in 0.5.74, which caused the RTD
version widget to be rendered at the bottom of the page.
=> docs: update extra css files in html_context of the theme

CHANGES.rst, croud/config.py, croud/parser.py, croud/printer.py, docs/commands/config.rst, tests/unit_tests/test_commands.py
Example:
```console
$ croud config get env
+-------+
| env   |
|-------|
| dev   |
+-------+
$ croud config get env -o json
[
{
"env": "dev"
}
]
```
=> make the `config get` commands respect the output format

CHANGES.rst, croud/monitoring/grafana/commands.py, croud/rest.py, tests/unit_tests/test_commands.py, tests/unit_tests/test_rest.py, tests/unit_tests/util/__init__.py, tests/unit_tests/util/fake_server.py
=> Fixed redirect error and error response handling in Grafana REST API

CHANGES.rst
- Fixed API redirect and error response bug for ``monitoring grafana`` command.
=> prepare release 0.11.1

tests/unit_tests/test_authentication.py
This is required to ensure we're not actually hitting a real API
endpoint.
=> Mock out event loop when running logout test

CHANGES.rst, croud/__main__.py, croud/cmd.py, croud/products/commands.py, docs/commands/index.rst, docs/commands/products.rst, tests/unit_tests/test_commands.py
this command list all available products in the current region.
usage:
croud products list --kind "cluster" --region "eastus.azure"
=> Added croud products list command

croud/rest.py, tests/unit_tests/test_rest.py, tests/unit_tests/util/fake_server.py
When a request returns 204 it has no body, which returns an error
message saying that the request was not successful. If a response has an
empty body it will now check if the return code is 204 and returns
success.
=> Fix console output for delete requests

CHANGES.rst, croud/__main__.py, croud/cmd.py, croud/consumers/commands.py, croud/util.py, docs/commands/consumers.rst, tests/unit_tests/test_commands.py, tests/unit_tests/test_util.py
=> Add consumers delete command

croud/rest.py, tests/unit_tests/test_rest.py
This commit fixes an unreleased regression of the console output of the
`consumers delete` command that printed a response table instead of a
simple success message.
Output before the commit:
```console
$ croud consumers delete --consumer-id ... --yes
+-----------+
| success   |
|-----------|
| TRUE      |
+-----------+
```
Output after the fix:
```console
$ croud consumers delete --consumer-id ...
Are you sure you want to delete the consumer? [yN] y
==> Success: Consumer deleted.
```
=> fix a regression of the output when deleting resources

docs/commands/clusters.rst
Added documentation about backups when deleting a CrateDB Cluster.
=> Added documentation about backups when deleting a CrateDB Cluster

CHANGES.rst, croud/__main__.py, croud/clusters/commands.py, tests/unit_tests/test_commands.py
The project ID is not required by the back-end to identify a cluster.
The cluster ID is sufficient. The project ID is effectively ignored.
=> Removed unneeded --project-id argument from clusters scale

DEVELOP.rst, dev/tools/create_tag.sh, setup.py
Croud used to use [setuptools_scm](https://pypi.org/project/setuptools-scm/)
for handling the Python package version instead of declaring it manually
in the `setup.py` file.
This commit removes the setup requirement and switches to manually
declared versions. The reason for that is to use the same tooling for
tagging and releasing this package, that we use also for other packages.
This change therefore also adds a script to create a tag automatically,
which is located in `dev/tools/create_tag.sh`.
=> Replace setuptools_scm with manual version management

.travis.yml, README.rst
This commits changes the .travis.yml so that coverage reports are also
uploaded to codecov.io for analysis.
The status of codecov is displayed as a badge in the README.
=> Add codecov integration

croud/config.py, croud/gql.py, croud/login.py, croud/logout.py, croud/rest.py, croud/server.py, tests/unit_tests/test_authentication.py, tests/unit_tests/test_server.py
The Configuration class is responsible for reading from and writing to
the configuration file.
However it was also misused for "temporarily" storing the current
context so it is available across method calls but not persisted to
disk.
This PR removes the current_context property from the class.
=> Remove current_context from configuration object

.mergify.yml
Mergify can automatically merge branches that were reviewed and pass
CI tests by slapping the `ready-to-merge` label on it.
=> Add Mergify.io integration

CHANGES.rst, croud/__main__.py, croud/clusters/commands.py, docs/commands/clusters.rst, tests/unit_tests/test_commands.py
* Added `croud clusters upgrade` command to update an existing CrateDB cluster to a later hotfix/patch version.
This PR depends on changes in the backend. https://github.com/crate/cloud-app/pull/815
=> Added clusters upgrade command

requirements-docs.txt
This reverts commit 2d62c68ec12be8eff9efd9aaba796ac018907340.
The `.` in the `requirements-docs.txt` is required so that the `croud`
project itself is also installed into the virtualenv when running
```console
$ env/bin/pip install -e requirements-docs.txt
```
Otherwise the `bin/spinx` command would error with following message if
the project had not been installed into the virtualenv before with
`env/bin/pip install -e .`:
```console
Warning, treated as error:
/home/christian/sandbox/crate/croud/docs/commands/authentication.rst:17:Failed to import "get_parser" from "croud.__main__".
No module named 'croud'
```
=> Revert "fix erroneous line"

docs/commands/clusters.rst
The example command in the documentation is showing the wrong parameter
`name`, which is not valid. Updated the documentation to show the actual
parameter `cluster-name`.
=> Update croud cluster deploy command example

CHANGES.rst, croud/rest.py, tests/unit_tests/test_rest.py
the `errors` part of an error message was not printed, when the error contained a `message`.
this caused the schema validation error to be incomprehensible.
=> improved printing of error messages

CHANGES.rst, croud/users/roles/commands.py, docs/commands/users.rst, tests/unit_tests/test_commands.py
- Updated users roles list command to use REST instead of GraphQL.
This PR depends on changes in the backend. https://github.com/crate/cloud-app/pull/827
=> Updated users roles list command to use REST instead of GraphQL

croud/__main__.py, croud/organizations/commands.py, docs/commands/organizations.rst, tests/unit_tests/test_commands.py
The command for deleting an organization is `croud organizations delete
--org-id <id>`.
```console
$ croud organizations delete
The following arguments are required: --org-id
Usage: croud organizations delete [-h] [-y] --org-id ORG_ID
[--region {bregenz.a1,westeurope.azure,eastus2.azure,eastus.azure}]
[--env {local,prod,dev}]
[--output-fmt {json,table}]
Required Arguments:
--org-id ORG_ID       The organization ID to use.
Optional Arguments:
-h, --help            Show this help message and exit.
-y, --yes
--region {bregenz.a1,westeurope.azure,eastus2.azure,eastus.azure}, -r {bregenz.a1,westeurope.azure,eastus2.azure,eastus.azure}
Temporarily use the specified region that command will
be run in.
--env {local,prod,dev}, -e {local,prod,dev}
Switches auth context.
--output-fmt {json,table}, …
```
=> Add command to delete an existing organization

CHANGES.rst, croud/__main__.py, croud/projects/commands.py, croud/users/roles/commands.py, docs/commands/projects.rst, tests/unit_tests/test_commands.py
```
$ croud projects delete --help                                           
Usage: croud projects delete [-h] -p PROJECT_ID [-y]
[--region {eastus2.azure,eastus.azure,bregenz.a1,westeurope.azure}]
[--env {dev,prod,local}]
[--output-fmt {json,table}]
Required Arguments:
-p PROJECT_ID, --project-id PROJECT_ID
The project ID to use.
Optional Arguments:
-h, --help            Show this help message and exit.
-y, --yes
--region {eastus2.azure,eastus.azure,bregenz.a1,westeurope.azure}, -r {eastus2.azure,eastus.azure,bregenz.a1,westeurope.azure}
Temporarily use the specified region that command will
be run in.
--env {dev,prod,local}, -e {dev,prod,local}
Switches auth context.
--output-fmt {json,table}, -o {json,table}
Change the formatting of the output
```
=> Added command to delete projects

croud/organizations/users/commands.py, tests/unit_tests/test_commands.py
The user_id parameter that was used to add a org_role to a user no longer reflects that it can be a user-id or a email address. Moving forward the parameter will be user.
=> Updated the user_id parameter to user in org_users_add

CHANGES.rst, croud/parser.py, croud/printer.py, tests/unit_tests/test_printer.py
The output format can be changed to YAML using the `-o yaml` argument.
=> Add support for YAML output

CHANGES.rst, croud/__main__.py, croud/config.py, croud/login.py, croud/logout.py, croud/organizations/commands.py, croud/organizations/users/commands.py, croud/projects/commands.py, croud/users/commands.py, croud/util.py, tests/unit_tests/test_authentication.py, tests/unit_tests/test_util.py
=> Store a user's organization ID upon login and use as fallback for --org-id

croud/clusters/commands.py, croud/config.py, croud/consumers/commands.py, croud/login.py, croud/me.py, croud/monitoring/grafana/commands.py, croud/organizations/commands.py, croud/organizations/users/commands.py, croud/printer.py, croud/products/commands.py, croud/projects/commands.py, croud/projects/users/commands.py, croud/rest.py, croud/users/roles/commands.py, tests/unit_tests/test_authentication.py, tests/unit_tests/test_commands.py, tests/unit_tests/test_printer.py, tests/unit_tests/test_rest.py, tests/unit_tests/test_util.py
- Updated the feedback messages of several commands.
- Added the `print_response` function to be able to print the feedback messages of the
commands.
- Reworked REST client:
- The `_fetch` function is now part of `fetch` and returns the response data and errors.
- Removed the `client.print` function.
- Removed the private fields `_data`, `_error` and `_output_fmt`.
=> Reworked REST client and printing

croud/login.py, croud/util.py, tests/unit_tests/test_authentication.py, tests/unit_tests/test_util.py
=> Store organization ID for superusers but require --org-id when using --sudo

CHANGES.rst, setup.py
- Updated ``croud users list`` to include all user roles.
- Depreated ``--no-org`` argument to ``croud users list`` in favor of ``--no-roles``.
- Added the ``croud projects users list`` command to list all user within a project.
- Added the ``croud organizations users list`` command to list all user within an
organization.
- Added the optional ``--sudo`` argument to be able to specify when a command should
be run as ``superuser``.
- The ``-org-id`` parameter is now optional for non-superusers. Upon login, a
user's organization will be retrieved and stored in the configuration file.
Whenever the ``--org-id`` parameter is needed, a fallback to the default
organization will be made.
- Added support for YAML output. It can be specified with the ``-o yaml``
argument.
=> Prepare release 0.17.0

setup.py
With Python 3.8 not too far away, it's time to drop version of PyYAML
that won't support 3.8 and upgrade to a recent version:
DeprecationWarning: Using or importing the ABCs from 'collections'
instead of from 'collections.abc' is deprecated, and in 3.8 it will
stop working
=> Bump PyYAML to modern version

CHANGES.rst, croud/clusters/commands.py
The table columns were inadvertently changed in
028151464ead6a524f9e4243ebad717efebe9b8d as part of a larger
refactoring.
=> Fix column selection for clusters upgrade command

CHANGES.rst, croud/rest.py, tests/test_rest.py
Print only a sensible error message instead the full traceback.
=> Handle client networking errors correctly

croud/__main__.py
Refs 9a08bb41b41bc26a740517814139b62d3ed81ace
```
$ croud organizations -h               
Usage: croud organizations [-h] {create,list,edit,delete,auditlogs,users} ...
Available Commands:
create      Create a new organization.
list        List all organizations the current user has access to.
edit        Edit the specified organization.
delete      Delete the specified organization.
auditlogs   Show audit logs for an organization.
users       Manage users in an organization.
Optional Arguments:
-h, --help  Show this help message and exit.
```
```
$ croud organizations auditlogs list -h
Usage: croud organizations auditlogs list [-h] [--action ACTION] [--from FROM]
[--to TO] [--org-id ORG_ID]
[--region {westeurope.azure,eastus2.azure,bregenz.a1,eastus.azure}]
[--env {prod,dev,local}] …
```
=> Fix help text in new auditlog command

.github/workflows/release.yaml, DEVELOP.rst
The Github action job is triggered whenever a tag is pushed. It builds
the source distribution package and the wheel and uploads them to PyPi.
=> Add Github action to build & upload to PyPi

CHANGES.rst, setup.py
**Attention, this release contains a breaking change to the configuration file.**
Since the new profiles are incompatible with the existing configuration, you are asked to delete the existing configuration file when you run croud for the first time after the update.
Please run `croud config --help` or `croud config profiles --help` thereafter or conduct the documentation for further information how to use the profiles.
=> Prepare release 0.23.0

croud/parser.py, docs/commands/users.rst, docs/user-roles.rst
Adds warning to Croud docs section on user commands that these are for Cloud staff (superusers) only and are only listed because they are currently present in the argparse configuration for --help. Corresponds to [this old story/impediment](https://trello.com/c/2uUClYL5/251-fix-customer-facing-docs-for-croud-users-command).
=> Warning that users commands are for superusers only

CHANGES.rst, croud/consumers/commands.py, docs/commands/consumers.rst, tests/commands/test_consumers.py
=> Deprecated the croud consumers commands

CHANGES.rst, croud/__main__.py, croud/login.py, docs/commands/authentication.rst, tests/commands/test_login.py
CrateDB Cloud allows two different authentication methods via two
different providers at the moment:
* username + password via Amazon Cognito
* OAuth via Azure Active Directory
The optional `--idp` argument allows for choosing the identity provider
for the login. It defaults to username+password via Cognito (which was
the only possible way up to now).
=> Add --idp argument for login

CHANGES.rst, croud/config/schemas.py, croud/organizations/auditlogs/commands.py, croud/organizations/users/commands.py, croud/printer.py, croud/projects/users/commands.py, croud/users/commands.py, docs/configuration.rst, tests/test_config_schemas.py, tests/test_printer.py
`-o wide` can be used to print the full table as opposed to the cherry picked columns the argument `-o table` provides.
=> Support for wide tabular output format, where all fields are displayed

.gitignore, CHANGES.rst, croud/__main__.py, croud/api.py, croud/config/commands.py, croud/config/configuration.py, croud/config/schemas.py, croud/login.py, docs/commands/regions.rst, docs/configuration.rst, tests/commands/test_config.py, tests/test_configuration.py
This allows us to set a default region (which can also be __any__) and not have to ever specify one when running any commands.
=> Added an (optional) region param

CHANGES.rst
in response to https://github.com/crate/croud/pull/305#pullrequestreview-541852484
I realized the CHANGES.rst file does not use any double newlines before headers, per our RST style guide. so it makes sense to not add a single one on https://github.com/crate/croud/pull/305 (which would introduce an inconsistency in style). so I thought I'd quickly prepare this PR to fix the style throughout the whole file :)
=> Add empty newlines above headers

CHANGES.rst, croud/__main__.py, croud/clusters/commands.py, croud/organizations/auditlogs/commands.py, croud/organizations/commands.py, croud/organizations/users/commands.py, croud/products/commands.py, croud/projects/commands.py, croud/projects/users/commands.py, croud/subscriptions/commands.py, croud/users/commands.py, croud/users/roles/commands.py, tests/commands/test_clusters.py, tests/commands/test_organizations.py, tests/commands/test_projects.py, tests/commands/test_subscriptions.py
This commit adds a new subcommand `get` for the following resources:
* `clusters`
* `organizations`
* `projects`
* `subscriptions`
The command requires a single positional argument `ID` and it returns a
single item of the requested resource by fetching the item by its ID
using the `GET /api/v2/{resource}/{id}/` API endpoints.
Example:
```console
$ croud clusters get 205815c3-230f-442d-99e8-1c34bd717845
...
```
=> Get resources by their ID

croud/printer.py
Fix loading indicator also to disappear if just a message is printed.
To avoid something like that, where the loading indicator doesn't disappear after the command has finished:
=> Fix loading indicator to also disappear if just a message is printed

CHANGES.rst, croud/__main__.py, croud/regions/commands.py, docs/commands/regions.rst, tests/commands/test_regions.py
Add subcommand to fetch a deployment manifest for an edge region.
=> Add subcommand to fetch a deployment manifest for an edge region

croud/__main__.py, croud/regions/commands.py, tests/commands/test_regions.py
Mark edge region endpoints as experimental.
=> Mark edge region endpoints as experimental

croud/__main__.py, croud/regions/commands.py, docs/commands/regions.rst, tests/commands/test_regions.py
Because now, after creating the region, a command is shown to the user that does the whole region installation without Croud.
=> Remove regions generate manifest command

CHANGES.rst, croud/printer.py, croud/regions/commands.py, setup.py, tests/commands/test_regions.py, tests/test_printer.py
- Corrected install edge-region script command when creating a new region
- Added a new raw format printer
- Added a test for the returned install command
- Changed the command to use `wget` instead of curl
=> Corrected install edge-region script command when creating a new region

CHANGES.rst, croud/printer.py, croud/regions/commands.py, setup.py, tests/commands/test_regions.py, tests/test_printer.py
.. as formatprinters only support JsonDict flavors and not simple strings.
=> Fixed linter errors. Removed RawFormatPrinter

docs/conf.py
The `sphinx-docs-theme` specifies a list of default Sphinx extensions in the [src/crate/theme/rtd/conf/__init__.py][1] file.
The `conf.py` file in this Sphinx project also specified a list of Sphinx extensions. However, the way this was done meant that a direct assignment was overwriting the default value of the extensions variable (imported at the start of the file).
As a consequence, the Croud docs have not yet picked up any of the following improvements:
- Intersphinx support
- PlantUML support
- Open Graph support
- [Sphinx copy button][2] support
This change replaces the direct assignment with a list append operation and removes a redundant extension (`sphinx_sitemap`) that is already present in the default list.
I have verified that as a result of this change, the Sphinx copy button …
=> Fix Sphinx extensions configuration

CHANGES.rst, croud/__main__.py, croud/clusters/commands.py, docs/commands/clusters.rst, tests/commands/test_clusters.py
Added new subcommand ``clusters restart-node`` that allows superusers to restart a single node in a cluster.
=> Add new command to restart individual nodes

CHANGES.rst, croud/__main__.py, croud/clusters/commands.py, docs/commands/clusters.rst, tests/commands/test_clusters.py
Added new subcommand ``clusters set-deletion-protection`` that allows superusers and organization admins to set the deletion protection status of a cluster.
=> Add new command to set the deletion protection status of a cluster

CHANGES.rst, croud/__main__.py, croud/projects/commands.py, tests/commands/test_projects.py
Adding `--backup-location-endpoint-url` allows specifying a custom S3 endpoint (eg. http://minio.svc.local:9000) for cluster backup. This setting is on `project` level.
=> Allow specifying an S3 backup-location-endpoint-url for projects 

CHANGES.rst, croud/__main__.py
The cluster disk size is calculated on a binary basis. The help message is improved to reflect it.
=> Improve 'help' message for disk size

CHANGES.rst, croud/config/configuration.py, docs/commands/config.rst, tests/commands/test_config.py, tests/test_configuration.py
It makes no sense to have those region-specific endpoints, as they all point to the same thing.
=> Sanitize the default config

.mergify.yml
https://blog.mergify.com/strict-mode-deprecation/
=> Mergify have deprecated the strict merging mode

croud/clusters/commands.py, docs/commands/clusters.rst
- Will not print the whole response table but individual statuses
- Will not print statuses if they have not changed
=> Some tweaks to the status reporting of upgrades

CHANGES.rst, croud/clusters/commands.py, croud/clusters/exceptions.py, docs/commands/clusters.rst, tests/commands/test_clusters.py
Use the same status reporting for scaling operations as it is already used for upgrades.
https://github.com/crate/cloud/issues/421
=> Added status check to the scale handler

croud/clusters/commands.py, docs/commands/clusters.rst, tests/commands/test_clusters.py, tests/commands/test_organizations.py
Use the same status reporting for cluster creation and ip-whitelist updates as it is already used for cluster scaling and upgrades.
https://github.com/crate/cloud/issues/439
=> Add status checks to cluster creation and ip-whitelist update

CHANGES.rst, croud/__main__.py, croud/clusters/commands.py, docs/commands/clusters.rst, setup.py, tests/commands/test_clusters.py
Added new subcommand `clusters expand-storage` that allows superusers and organization admins to expand the disk size of a cluster.
=> Add new command to expand disk size of a cluster

docs/commands/clusters.rst
- Adds warning to Croud command `clusters expand-storage` that if you exceed a storage increment, you will pay the price of the next increment
=> Add increment warning to cluster expand-storage command

CHANGES.rst, croud/__main__.py, croud/clusters/commands.py, docs/commands/clusters.rst, tests/commands/test_clusters.py
Added new subcommand `clusters set-suspended-state` that allows superusers, organization admins and project admins to suspend or resume a cluster.
=> Add new command to suspend or resume a cluster

CHANGES.rst, croud/__main__.py, croud/subscriptions/commands.py, docs/commands/subscriptions.rst, tests/commands/test_subscriptions.py
Added new subcommand `subscriptions create` that allows superusers to create custom subscriptions. E.g. a subscription of type `contract`
=> Add subscriptions create subcommand

CHANGES.rst, setup.py
=> Prepare release 0.38.0

CHANGES.rst, croud/__main__.py, croud/api.py, croud/subscriptions/commands.py, docs/commands/subscriptions.rst, tests/commands/test_subscriptions.py
Also updated subscriptions list to show the org_id, as it's useful if the user has multiple orgs.
And fixed the LOG_API param to correctly use Python booleans.
=> Added new command to cancel Stripe subscriptions

.github/CODEOWNERS, CHANGES.rst, croud/__main__.py, croud/clusters/commands.py, docs/commands/clusters.rst, tests/commands/test_clusters.py
`clusters change-product` to `clusters set-product` and `clusters change-backup-schedule` to `clusters set-backup-schedule`. Note that technically this is a breaking change, so we should probably bump `croud` to version 1.0.0 upon the next release.
=> Unified some commands in the clusters namespace

CHANGES.rst, setup.py
- Added support for listing and restoring snapshots, including cloning clusters.
=> Prepare release 1.2.0

.github/workflows/docs.yml, .github/workflows/main.yml, CHANGES.rst, croud/__main__.py, croud/clusters/commands.py, setup.cfg, setup.py, test-requirements.txt, tests/commands/test_clusters.py
This fixes an issue where no snapshots could be listed if the cluster was suspended for longer than 2 days.
=> Added an ability to specify the `--days-ago` argument to `snapshots list`

CHANGES.rst, croud/__main__.py, croud/subscriptions/commands.py, docs/commands/subscriptions.rst, tests/commands/test_subscriptions.py
depends on https://github.com/crate/cloud-api/pull/2436
Change the API url for cancelling subscriptions from `/api/v2/stripe/subscriptions/<subscription_id>/` to `/api/v2/subscriptions/<subscription_id>/` which also allows cancelling contract subscriptions.
https://github.com/crate/cloud/issues/1131
=> Add support for cancelling contract subscriptions

CHANGES.rst, croud/clusters/commands.py
This is useful to know when listing clusters.
=> Added the suspended state to croud cluster responses.

CHANGES.rst, croud/clusters/commands.py, tests/commands/test_clusters.py
- Changed import jobs status to show the error message if an import fails.
- Added the URL to the import jobs list output.
=> Slightly spruced up import job handling

CHANGES.rst, croud/__main__.py, croud/clusters/commands.py, croud/organizations/commands.py, docs/commands/clusters.rst, docs/commands/organizations.rst, tests/commands/test_clusters.py, tests/commands/test_organizations.py
This adds the following commands that allow organization admins to export data from crateDB and manage these export jobs.
- `$ croud clusters export-jobs create --cluster-id {cluster_id} --table {table} --file-format {format}` - exports data from the given table in the given format and displays a link to download the exported file.
- `$ croud clusters export-jobs create --cluster-id {cluster_id} --table {table} --file-format {format} --save-as {target_file}` - exports data from the given table in the given format and downloads the file to the given location
- `$ croud clusters export-jobs list --cluster-id {cluster_id}` - lists all export jobs for the given cluster
- `$ croud clusters export-jobs delete --cluster-id {cluster_id} --export-job-id {export_job_id}` - deletes the given export …
=> Add support for cluster export jobs

CHANGES.rst, croud/__main__.py, croud/users/commands.py, tests/commands/test_users.py
=> add command to delete users

CHANGES.rst, croud/__main__.py, croud/clusters/commands.py, tests/commands/test_clusters.py
=> Import jobs now support S3 files using an org secret

CHANGES.rst, croud/clusters/commands.py, croud/printer.py, docs/commands/clusters.rst, tests/commands/test_clusters.py
- Added documentation for all import jobs commands.
- Fixed ``import-job create from-url`` throwing an error despite working.
=> Added import job documentation

CHANGES.rst, croud/clusters/commands.py
=> A couple of small bugfixes

CHANGES.rst, setup.py
- Added support for listing, deleting and creating organization secrets.
- Added support in import jobs for private S3 files using organization secrets.
- Added documentation for all import jobs commands.
- Fixed ``import-job create from-url`` throwing an error despite working.
- Added support for showing import job progress.
- Added the ``--transformations`` argument for import jobs.
- Moved import and export jobs into their own section in croud docs.
- Fixed a bug preventing s3 imports from working (due to the endpoint).
- Correctly showing percent for import jobs, and not showing for export jobs.
=> Prepare release 1.8.0

CHANGES.rst, croud/__main__.py, croud/clusters/commands.py, croud/organizations/commands.py, tests/commands/test_clusters.py, tests/commands/test_organizations.py
- Added support for organization secrets of type Azure.
- Added support for importing jobs from Azure Blob Storage.
=> Support for Azure secrets and blob Storage import jobs

CHANGES.rst, croud/__main__.py
Changed the documentation strings to describe the new behaviour of the `create_table` parameter.
=> Import jobs can now optionally add columns

CHANGES.rst, setup.py
- Import jobs can now optionally add columns to the schema if the `create_table`
parameter is set to `true`.
=> Prepare release 1.10.1

CHANGES.rst, croud/__main__.py, croud/config/configuration.py, croud/config/schemas.py, croud/scheduledjobs/commands.py, croud/util.py, docs/commands/index.rst, docs/commands/scheduled-jobs.rst, tests/commands/test_scheduled_jobs.py
=> Added ability to schedule sql jobs

CHANGES.rst, croud/__main__.py, croud/cloud_configurations/commands.py, docs/commands/cloud-configurations.rst, docs/commands/index.rst, tests/commands/test_cloud_configurations.py
Add superuser commands to manage cloud configurations
- `croud cloud-configurations list --sudo [--org-id ORG_ID]` lists all available configuration keys/values. Optionally with org specific overrides.
- `croud cloud-configurations get --key KEY --sudo [--org-id ORG_ID]` get the value of a single configuration key. Optionally with org specific overrides.
- `croud cloud-configurations set --key KEY --value VALUE --sudo [--org-id ORG_ID]` set the value of a configuration key globally or create an org override if an `org-id` is set.
=> Add commands to manage cloud-configurations

CHANGES.rst, setup.py
- Prepare release 1.11.1
- Update doc for ``clusters restart-node`` because it is not superuser only anymore.
- Upgrade docs build action Python version to 3.11.
=> Prepare release 1.11.1

CHANGES.rst, croud/__main__.py, croud/cloud_configurations/commands.py, docs/commands/cloud-configurations.rst, tests/commands/test_cloud_configurations.py
This adds an optional argument `--user-id` to `croud cloud-configurations get|set|list` to get or set user specific configuration values (similar to what is already done on organization level with the `--org-id` arg).
=> Add support for overriding cloud-configurations per user

.github/dependabot.yml, .gitignore, .pre-commit-config.yaml, croud/api.py, croud/printer.py, croud/regions/commands.py, croud/server.py, pyproject.toml, setup.cfg, setup.py, tests/commands/test_clusters.py, tests/test_api.py, tests/test_printer.py, tests/util/fake_cloud.py
Update to the most recent version of mypy, in order to support the update to Python 3.11 on a subsequent iteration.
=> Update to mypy 1.10

.github/CODEOWNERS, croud/__main__.py, docs/commands/clusters.rst
Added a note how to set `--subscription-id` argument when deploying free clusters.
=> Add note for deploying free clusters

.github/CODEOWNERS, CHANGES.rst, setup.py
=> update CODEOWNERS and replaced `pkg_resources` with `packaging`

.github/workflows/release.yaml
Follow-up to https://github.com/crate/croud/pull/521 This should fix:
```
Traceback (most recent call last):
File "setup.py", line 24, in <module>
from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```
=> Add `packaging` to github release workflow

README.rst, setup.py
Pypi upload seems to fail when images have a `scale` factor. in this case `twine` reports:
```
$ twine check dist/*
Checking dist/croud-1.12.0-py2.py3-none-any.whl: FAILED
ERROR    `long_description` has syntax errors in markup and would not be rendered on PyPI.                                                                                                                          
line 50: Warning: Cannot scale image!                                                                                                                                                                      
Could not get size from "https://github.com/crate/croud/actions/workflows/docs.yml/badge.svg":                                                                                                           
Requires …
```
=> Fix README.rst for pypi upload

.github/workflows/docs.yml, .github/workflows/main.yml, .github/workflows/release.yaml, .readthedocs.yml, README.rst, croud/__init__.py, croud/__main__.py, croud/util.py, setup.py, test-requirements.txt, tox.ini
A few adjustments to prepare unlocking Python 3.12 and eventually 3.13.
The patch mainly phases out use of `pkg_resources` and `distutils.util`.
=> Dependencies: Modernize to prepare unlocking more recent Python versions

.github/workflows/docs.yml, .github/workflows/main.yml, .github/workflows/release.yaml, .readthedocs.yml, CHANGES.rst, setup.py, tests/util/fake_cloud.py, tox.ini
In `tests.util.fake_cloud.FakeCrateDBCloudServer`, `ssl.wrap_socket()` is no longer supported.
That other PR needs to be merged first.
- GH-543
=> CI: Add support for Python 3.12 and 3.13

.github/workflows/main.yml, CHANGES.rst, DEVELOP.rst, setup.py, tox.ini
Python 3.8 reached EOL. and it is causing dependency upgrades to fail GH-546, GH-551
=> Drop support for Python 3.8

CHANGES.rst, croud/api.py, croud/config/configuration.py, croud/login.py, croud/organizations/commands.py, croud/printer.py, croud/projects/commands.py, croud/util.py
A few more refinements while working on headless mode support.
> `exit` is a helper for the interactive shell - `sys.exit` is intended for use in programs.
>
> -- https://stackoverflow.com/q/6501121
- https://github.com/crate/cratedb-toolkit/pull/81
- GH-562
=> Chore: Fix `exit` vs. `sys.exit`

CHANGES.rst, croud/clusters/commands.py, docs/commands/clusters.rst
`croud clusters deploy` yielded duplicate output, which is detrimental when using `--output-fmt=json`, because the output can not be parsed by downstream programs.
- https://github.com/crate/cratedb-toolkit/pull/81#pullrequestreview-1737914416
=> Fix duplicate JSON output in `croud clusters deploy`

docs/configuration.rst, docs/getting-started.rst, docs/user-roles.rst
Page local TOC are now redundant with the right hand side TOC.
=> Remove page local toc

CHANGES.rst, setup.py
- Dropped support for Python 3.8.
- Client: Accounted for edge-case when login token is an empty string
- Fixed `exit()` vs. `sys.exit()` invocations to improve library use
- Fixed duplicate JSON output in croud clusters deploy
- Headless mode: Started accepting environment variables `CRATEDB_CLOUD_API_KEY` and `CRATEDB_CLOUD_API_SECRET` to authenticate with API keys when no `croud.yaml` configuration file exists.
- Dependencies: Relaxed version pinning to make package compatible with others
- Dependencies: Migrated from ``appdirs`` to ``platformdirs``
=> Prepare release 1.14.0

.github/workflows/release.yaml
- Fixed the Github action using an outdated dependency that lead it to fail.
- Note the project was released by manually creating the 1.14.0 tag from this branch, to avoid polluting main in case the fix didn't work.
=> Updated release GitHub action
