- croud/printer.py
- croud/typing.py
- mypy.ini
- pytest.ini
- setup.py
- tests/unit_tests/test_gql.py
Mypy is a tool that lets us use static type checking within python, using typing annotations.
> Add mypy type checking as part of pytest

- CHANGES.rst
- setup.py
```bash
$ croud --version       
CROUD 0.1.dev10+g5d7ab7e
```
> Add initial CHANGES and proper scm versioning

- CHANGES.rst
- croud/me.py
- croud/printer.py
- croud/session.py
- setup.py
- tests/unit_tests/test_printer.py
```
$ croud me --env dev -o tabular
+-----------------+------------------------------+-----------------+
| email           | username                     | name            |
|-----------------+------------------------------+-----------------|
| hoschi@crate.io | Google_104209952803880732135 | Hoschi Galoschi |
+-----------------+------------------------------+-----------------+
```
> Add tabular output format

- CHANGES.rst
- croud/__main__.py
- setup.py
This allows one to extend the functionality of croud by providing custom commands.
> [PROPOSAL] Load commands from `croud_commands` entry points.

- croud/__main__.py
```
$ croud -h       
usage: croud [-h] [--version] {login,logout,me} ...
A command line interface for CrateDB Cloud ☁
positional arguments:
{login,logout,me}
login            Performs an OAuth2 Login to CrateDB Cloud
logout           Performs a logout of the current logged in User
me               Prints the current logged in user
optional arguments:
-h, --help         show this help message and exit
--version          show program's version number and exit
```
```
$ croud --version
croud 0.2.1.dev3+gdf82e23.d20181130
```
> Consistify help output

- croud/__main__.py
- croud/cmd.py
- croud/config.py
- croud/env.py
- croud/login.py
- croud/logout.py
- croud/me.py
- croud/projects/list.py
- setup.py
- tests/unit_tests/test_cmd.py
- tests/unit_tests/test_commands.py
In order to have subcommands for entities it's necessary to set up namespaces for argh
> Added namespaces template

- DEVELOP.rst
- pytest.ini
- setup.py
- test-requirements.txt
- tox.ini
requires https://github.com/crate/jenkins-dsl/pull/562 for CI support.
> Add tox.ini to run test against multiple python envs

- CHANGES.rst
- croud/__main__.py
- croud/clusters/list.py
- croud/cmd.py
- croud/util.py
- tests/unit_tests/test_commands.py
This lists clusters for a current user, in a specified region, and can be filtered by project ID
> Added clusters subcommand

- CHANGES.rst
- croud/__main__.py
- croud/cmd.py
- croud/users/roles/add.py
- tests/unit_tests/test_commands.py
This command is only usable by super users
> Added users roles add sub command

- .gitignore
- DEVELOP.rst
- README.rst
- docs/.travis.yml
- docs/bootstrap.sh
- docs/docs/commands.txt
- docs/docs/conf.py
- docs/docs/getting-started.txt
- docs/docs/index.txt
- docs/requirements.txt
- tox.ini
In-depth docs for Croud now reside within the Croud repository
> Added sphinx docs

- CHANGES.rst
- croud/__main__.py
- croud/users/roles/remove.py
- tests/unit_tests/test_commands.py
This adds a subcommand to remove a role from a user if permitted.
> Added subcommand to remove a role from a user

- croud/__main__.py
- croud/cmd.py
- croud/gql.py
- croud/products/deploy.py
- croud/session.py
- docs/docs/commands.txt
- tests/unit_tests/test_commands.py
- tests/unit_tests/test_session.py
Implemented ``croud product deploy`` command.
> deploy cloud product

- CHANGES.rst
> add changelog for commit 3d1826636a138aadddfd102ade7545df6f0975bf

- croud/cmd.py
Changed the arguments with the boolean required due to @chaudum 's requested changes in #58
> Refactored arguments with boolean required

- docs/docs/commands.txt
Changed `Recognized options:` → `Available options:`
.. because it sounds more meaningful
> Refactored docs/commands

- docs/docs/commands.txt
> fix the documentation for the `products` command

- CHANGES.rst
- croud/__main__.py
- croud/cmd.py
- croud/gql.py
- croud/printer.py
- croud/projects/users/commands.py
- docs/docs/commands.txt
- tests/unit_tests/test_commands.py
- tests/unit_tests/test_gql.py
Implemented the following commands: 
* `croud projects users add` - add user to a project
* `croud projects users remove` - remove user from a project
They depend on the endpoints in the `cloud-app`
> Implemented projects users add/remove commands

- croud/users/roles/commands.py
- tests/unit_tests/test_commands.py
Reflects https://github.com/crate/cloud-app/pull/627/commits/50afd53d2ec2ff5799174e4c061e157e305d5a64
> "addRoleToUser" mutation returns success field only

- CHANGES.rst
- croud/__main__.py
- croud/cmd.py
- croud/consumersets/commands.py
- docs/docs/commands.txt
- tests/unit_tests/test_commands.py
- tests/unit_tests/util/__init__.py
Implemented the following command:
- ``croud consumer-sets list``
This PR depends on https://github.com/crate/cloud-product/pull/65
> implemented consumer-sets list

- CHANGES.rst
- croud/cmd.py
- tests/unit_tests/test_commands.py
while parsing required arguments
> fixed ``products deploy`` command which led to exception

- CHANGES.rst
- croud/cmd.py
> Fixed argument description of --role

- CHANGES.rst
> prepare release 0.9.0

- docs/docs/commands.txt
Added documentation for the following commands:
- `croud consumers deploy`
- `croud consumers list`
- `croud consumers edit`
> added consumers to the documentation

- test-requirements.txt
This will avoid future version conflicts.
> tests: nail test dependency versions

- CHANGES.rst
> Prepare 0.11.0

- CHANGES.rst
> Sync 0.11.1 release

- croud/clusters/commands.py
- croud/monitoring/grafana/commands.py
- croud/organizations/commands.py
- croud/projects/commands.py
- croud/rest.py
- croud/session.py
- tests/unit_tests/test_commands.py
- tests/unit_tests/util/__init__.py
Depends on crate/cloud-app#785
> Converted cluster listing and deploying to REST

- croud/clusters/commands.py
- croud/consumers/commands.py
- croud/session.py
- tests/unit_tests/test_commands.py
Depends on crate/cloud-app#788
The first commit is shared with #138.
> Converted consumer listing, deploying, and editing to REST

- CHANGES.rst
> prepare release 0.12.0

- CHANGES.rst
- croud/rest.py
- tests/unit_tests/test_rest.py
> removed the redundant error json

- CHANGES.rst
> prepare release 0.12.1

- CHANGES.rst
> reflect 0.12.1

- croud/printer.py
- tests/unit_tests/test_printer.py
> Separated individual printer classes for better testability

- CHANGES.rst
- croud/__main__.py
- croud/clusters/commands.py
- docs/commands/clusters.rst
- tests/unit_tests/test_commands.py
Usage:
croud clusters delete --cluster-id <id>
> Added command to delete clusters

- CHANGES.rst
- croud/clusters/commands.py
- croud/consumers/commands.py
> add region parameter to croud clusters delete command

- CHANGES.rst
> prepare release 0.13.0

- CHANGES.rst
> prepare release 0.12.3

- docs/commands/clusters.rst
> Fix rst markup in documentation of the clusters command

- CHANGES.rst
> prepare release 0.13.1

- CHANGES.rst
> reflect release 0.13.1

- CHANGES.rst
- croud/printer.py
- croud/rest.py
- tests/unit_tests/test_printer.py
> print an empty table when the query results in an empty list

- .travis.yml
- README.rst
- setup.py
This commit adds the `.travis.yml` to the project so tests are run on a
publicly available CI platform.
> Add configuration for Travis CI

- docs/getting-started.rst
this link has changed remotely
> fix PyPI link

- docs/commands/clusters.rst
> Add a note that `clusters upgrade` is superusers only

- docs/commands/index.rst
- docs/getting-started.rst
- docs/user-roles.rst
Changes headers from title case to sentence case.
> changes titles to sentence case

- CHANGES.rst
Commit 08808c2bcfaa6a5e1e7a6dea249e377f76bf2bd3
> Add changelog entry for organization deletion

- croud/clusters/commands.py
- croud/consumers/commands.py
- croud/me.py
- croud/monitoring/grafana/commands.py
- croud/organizations/commands.py
- croud/organizations/users/commands.py
- croud/products/commands.py
- croud/projects/commands.py
- croud/rest.py
The args env, region and output_fmt are now required and loaded over the static function "from_args".
> Updated croud rest client and commands args

- CHANGES.rst
- setup.py
> Prepare release 0.14.1

- CHANGES.rst
- setup.py
> Prepare release 0.15.0

- CHANGES.rst
- setup.py
> Prepare 0.15.1

- CHANGES.rst
> Sync 0.15.1

- docs/commands/organizations.rst
- docs/commands/projects.rst
> Update projects|organizations remove documentation

- CHANGES.rst
- croud/products/commands.py
- docs/commands/products.rst
> Add scaling information to `products list`

- CHANGES.rst
- croud/__main__.py
- croud/clusters/commands.py
- croud/cmd.py
- tests/unit_tests/test_commands.py
The channel argument is needed to be able to specify if the version should be a stable/testing/nightly version.
> Added the channel argument

- CHANGES.rst
- setup.py
> Prepare release 0.16.0

- setup.py
> Post release bump

- CHANGES.rst
- croud/parser.py
- croud/rest.py
- tests/unit_tests/test_parser.py
- tests/unit_tests/test_rest.py
- tests/unit_tests/util/fake_server.py
> Added the --sudo argument

- CHANGES.rst
> Sync 0.15.2 release notes

- croud/login.py
- croud/rest.py
- tests/unit_tests/test_rest.py
> Fixed the error when using the format argument

- CHANGES.rst
- croud/__main__.py
- croud/parser.py
- tests/unit_tests/test_parser.py
> Fixed a bug using the croud config commands

- CHANGES.rst
- croud/organizations/commands.py
- tests/unit_tests/test_commands.py
> Fix bug in organization delete

- CHANGES.rst
- setup.py
> Prepare release 0.17.1

- CHANGES.rst
> Reflect release 0.17.1

- CHANGES.rst
- setup.py
> F/prepare release 0.18.0

- CHANGES.rst
- setup.py
> prepare release 0.18.1

- CHANGES.rst
> Sync 0.18.1 release notes

- DEVELOP.rst
> Update `make` help output 

- .mergify.yml
> Fix Jenkins reference for Mergify integration

- .flake8
- .isort.cfg
Their contents is already present in the setup.cfg file
> Remove .isort.cfg and .flake8.cfg

- CHANGES.rst
- croud/__main__.py
- croud/organizations/auditlogs/commands.py
- docs/commands/organizations.rst
- tests/commands/test_organizations.py
> Add command to list auditlogs

- CHANGES.rst
- setup.py
> Mh/prepare 0.19.0

- CHANGES.rst
- setup.py
> Prepare release 0.19.1

- CHANGES.rst
> Sync 0.19.1 release notes

- CHANGES.rst
- croud/__main__.py
- croud/me.py
- croud/parser.py
- docs/commands/me.rst
- tests/commands/test_me.py
> Add croud me edit command

- croud/me.py
- tests/commands/test_me.py
Refs ffc9d6fbb0607183619ad61eba5e7140d049d8e5
> Actually send the payload for croud me edit along

- CHANGES.rst
- setup.py
> Prepare release 0.20.0

- CHANGES.rst
- setup.py
> F/reflect release 0.20.0

- docs/commands/me.rst
> Updated response message for croud me edit to what the back-end returns

- CHANGES.rst
- setup.py
> Prepare release 0.21.0

- docs/commands/clusters.rst
Do we want a link to the Azure offer in the note to give readers a way to continue?
> Add note that cluster deployments are only available to superusers

- .github/workflows/main.yml
- .pre-commit-config.yaml
- .travis.yml
- DEVELOP.rst
- README.rst
- docs/conf.py
- setup.cfg
- setup.py
- test-requirements.txt
- tox.ini
Documentation is still linted on TravisCI
> Use Github Actions for running tests

- CHANGES.rst
- setup.py
> Prepare release 0.22.0

- setup.py
Bump version, reflect 0.22.0 release.
> Bump version, reflect 0.22.0 release.

- .mergify.yml
Head branches are deleted automatically by Github after merge.
> Remove deletion of head branch by mergify

- docs/commands/config.rst
- docs/commands/index.rst
Refs f6418c1c18019bf5d924731ca632188a12674dcf
> Update documentation around temporarily using a different region

- CHANGES.rst
- croud/parser.py
> Removed region validation because we want to add other regions

- docs/configuration.rst
> Fixed westeurope.azure endpoint in docs

- CHANGES.rst
- croud/config/configuration.py
- tests/test_configuration.py
> Ensure config directory exists before saving config

- CHANGES.rst
> Prepare release 0.23.1

- docs/commands/regions.rst
> Add eks1.eu-west-1.aws region to documentation

- croud/__main__.py
- croud/subscriptions/commands.py
- docs/commands/index.rst
- docs/commands/subscriptions.rst
- tests/commands/test_subscriptions.py
**Requires new back-end release**
> Add command to list all active subscriptions in an organization

- CHANGES.rst
- setup.py
> Reflect release 0.24.0

- CHANGES.rst
- setup.py
> Prepare release 0.24.0

- CHANGES.rst
- setup.py
> Prepare release 0.25.0

- CHANGES.rst
- setup.py
> Bump version, reflect 0.25.0 release.

- docs/commands/regions.rst
- docs/configuration.rst
Following code review by @matthijskrul
> A few minor adjustments

- CHANGES.rst
- croud/api.py
- tests/test_api.py
Will make it more distinguishable in the logs.
> Specify a custom User-Agent

- CHANGES.rst
- croud/__main__.py
- croud/regions.py
- docs/commands/regions.rst
- tests/commands/test_regions.py
> Added support for creating edge regions

- .mergify.yml
- CHANGES.rst
- croud/__main__.py
- croud/parser.py
- croud/printer.py
- croud/tools/spinner.py
- setup.py
This will show up in stderr and clear just before any output is printed. Just a nice gimmick.
https://user-images.githubusercontent.com/4594061/107764893-d71c2f00-6d28-11eb-9ad2-21417bce7545.mp4
> Add a spinner to Croud

- croud/util.py
Fix loading indicator to be hidden if it's asked for confirmation.
> Fix loading indicator to be hidden if it's asked for confirmation

- croud/__main__.py
- croud/regions/commands.py
- tests/commands/test_regions.py
Make backup location params optional.
> Make backup location params optional

- CHANGES.rst
- setup.py
> Prepare release 0.26.0

- croud/regions/commands.py
- tests/commands/test_regions.py
Update command to create a region to display the command to install the region.
> Update command to create a region to display the command to install the region

- croud/__main__.py
- croud/regions/commands.py
- tests/commands/test_regions.py
Fix wording of confirmation messages.
> Fix wording of confirmation messages

- tests/commands/test_regions.py
> Fixed tests by using config instead of hardcoded url

- CHANGES.rst
- croud/__main__.py
- croud/printer.py
- croud/regions.py
- croud/regions/commands.py
- docs/commands/regions.rst
- tests/commands/test_regions.py
Feature: Bootstrap edge region.
On hold since the backend endpoints need to be released first.
> Feature: Bootstrap edge region

- CHANGES.rst
- croud/__main__.py
- croud/regions/commands.py
- docs/commands/regions.rst
- tests/commands/test_regions.py
Added experimental support to delete edge regions
> Added experimental support to delete edge regions

- .gitignore
- CHANGES.rst
- croud/__main__.py
- croud/clusters/commands.py
- docs/commands/clusters.rst
- tests/commands/test_clusters.py
Note that this requires the corresponding API changes to be merged.
> Allow specifying custom hardware specs for edge products

- croud/clusters/commands.py
> Removing an accidental print statement

- .github/workflows/main.yml
- CHANGES.rst
- setup.py
- tox.ini
This patch adds testing on Python 3.9 on CI.
> Added support for Python 3.9.

- CHANGES.rst
- setup.py
> Prepare 0.27.0

- CHANGES.rst
- croud/regions/commands.py
- tests/commands/test_regions.py
> check region status before deleting it

- CHANGES.rst
- setup.py
> Prepare 0.28.0

- CHANGES.rst
- setup.py
> Prepare 0.29.0

- .github/workflows/main.yml
- CHANGES.rst
- README.rst
- setup.py
- test-requirements.txt
- tox.ini
> Added support for Python 3.10

- CHANGES.rst
- croud/clusters/commands.py
- tests/commands/test_clusters.py
- tests/util/__init__.py
> Added checking of upgrade status to the upgrade handler

- CHANGES.rst
- setup.py
> Prepare release 0.31.0

- CHANGES.rst
- croud/__main__.py
- croud/clusters/commands.py
- croud/projects/commands.py
- croud/regions/commands.py
- croud/subscriptions/commands.py
- tests/commands/test_clusters.py
- tests/commands/test_projects.py
- tests/commands/test_regions.py
- tests/commands/test_subscriptions.py
https://github.com/crate/cloud/issues/443
> added org-id to subscriptions, projects and clusters lists

- CHANGES.rst
- setup.py
> Prepare release 0.32.0

- CHANGES.rst
- setup.py
> Prepare release 0.33.0

- CHANGES.rst
- croud/__main__.py
- docs/commands/authentication.rst
- tests/commands/test_login.py
> Add github and google to the IDP list

- CHANGES.rst
- croud/__main__.py
> Fix help message for disk-size-gb argument

- CHANGES.rst
- croud/__main__.py
- croud/clusters/commands.py
- docs/commands/clusters.rst
- tests/commands/test_clusters.py
Depends on https://github.com/crate/cloud-api/pull/2117
> Use the new cluster provisioning API

- CHANGES.rst
- setup.py
> Prepare release 0.35.0

- CHANGES.rst
- croud/__main__.py
- croud/regions/commands.py
- docs/commands/regions.rst
- tests/commands/test_regions.py
> Update regions create command

- CHANGES.rst
- setup.py
> Prepare release 0.36.0

- docs/Makefile
- docs/commands/clusters.rst
- fix shown example
- clarify how the `unit` argument works
- edit Makefile to use Python3
> Fix the scale command example + clarify the `unit` argument

- docs/commands/index.rst
- docs/configuration.rst
- docs/getting-started.rst
- docs/index.rst
- docs/user-roles.rst
> Croud docs improvements

- CHANGES.rst
- croud/__main__.py
- croud/clusters/commands.py
- docs/commands/clusters.rst
- tests/commands/test_clusters.py
> Add clusters change-product subcommand

- CHANGES.rst
- setup.py
> Prepare release 0.37.0

- CHANGES.rst
- croud/__main__.py
- croud/clusters/commands.py
- tests/commands/test_clusters.py
https://github.com/crate/cloud/issues/922
> make subscription mandatory in cluster deployment

- .github/workflows/main.yml
- .pre-commit-config.yaml
- CHANGES.rst
- setup.py
> Dropped support for Python 3.6

- CHANGES.rst
- DEVELOP.rst
- croud/api.py
- croud/printer.py
Which allows debugging what API calls Croud is making.
> Added the `LOG_API` environment variable

- CHANGES.rst
- setup.py
> Prepare release 0.39.0

- CHANGES.rst
- setup.py
> Prepare release 0.40.0

- .github/workflows/main.yml
- CHANGES.rst
- croud/__main__.py
- croud/clusters/commands.py
- setup.py
- tests/commands/test_clusters.py
- tox.ini
> Add support to changes the backup schedule of clusters

- .github/dependabot.yml
- .pre-commit-config.yaml
- CHANGES.rst
- setup.py
> Added support for Dependabot

- CHANGES.rst
- setup.py
- tox.ini
This does not seem to be used - one less requirement to deal with.
> Removed tox

- CHANGES.rst
- setup.py
- tox.ini
Reverts crate/croud#405
Apparently it is used.
> Revert "Removed tox"

- CHANGES.rst
- setup.py
> Prepare release 1.0.0

- CHANGES.rst
- setup.py
> Prepare release 1.1.0

- CHANGES.rst
- croud/__main__.py
- croud/clusters/commands.py
- docs/commands/clusters.rst
- tests/commands/test_clusters.py
Added support to list and restore snapshots.
This include support for restoring snapshots from a different cluster from within the organization.
> Added support to list and restore snapshots

- CHANGES.rst
- setup.py
> Unfix version of tabulate

- CHANGES.rst
- setup.py
> Prepare release 1.2.1

- CHANGES.rst
- croud/regions/commands.py
- docs/commands/regions.rst
https://github.com/crate/cloud/issues/1080
> add org id to regions list

- .github/workflows/main.yml
- .pre-commit-config.yaml
- CHANGES.rst
- croud/__main__.py
- croud/clusters/commands.py
- setup.cfg
- setup.py
- tests/commands/test_clusters.py
> Added support to create and cancel import jobs

- croud/__main__.py
> Added support for parquet files on import jobs

- croud/__main__.py
- croud/clusters/commands.py
> Added support to list import jobs

- CHANGES.rst
- croud/__main__.py
- croud/clusters/commands.py
- tests/commands/test_clusters.py
> Creating an import job now waits for completion and gives progress feedback

- CHANGES.rst
- setup.py
> Prepare release 1.3.0

- docs/commands/clusters.rst
Docs for https://github.com/crate/cloud/issues/732
> Docs for testing/nightly deployments

- CHANGES.rst
- setup.py
> Prepare release 1.4.0

- CHANGES.rst
- croud/__main__.py
- croud/clusters/commands.py
- docs/commands/clusters.rst
- tests/commands/test_clusters.py
> Added option to deploy clusters without first having to create a project

- CHANGES.rst
- setup.py
> Prepare release 1.5.0

- CHANGES.rst
- setup.py
> Prepare release 1.6.0

- CHANGES.rst
- setup.py
> Prepare release 1.7.0

- .github/CODEOWNERS
> Add Romanas to CODEOWNERS

- CHANGES.rst
- croud/__main__.py
- croud/organizations/commands.py
- docs/commands/organizations.rst
- tests/commands/test_organizations.py
> Added support for listing, creating and deleting organization secrets

- CHANGES.rst
- setup.py
> Prepare release 1.9.0

- CHANGES.rst
- setup.py
> Prepare release 1.10.0

- croud/scheduledjobs/commands.py
> Rename grand central session cookie

- CHANGES.rst
- setup.py
> Prepare release 1.11.0

- CHANGES.rst
- docs/commands/clusters.rst
> Update doc for clusters restart-node

- .github/workflows/docs.yml
- CHANGES.rst
- docs/build.json
> upgrade crate docs version

- CHANGES.rst
- croud/__main__.py
- croud/organizations/commands.py
- docs/commands/organizations.rst
- tests/commands/test_organizations.py
> Add organization's customer commands

- CHANGES.rst
- setup.py
> Prepare release 1.12.0

- CHANGES.rst
- setup.py
> Prepare release 1.13.0

- CHANGES.rst
- croud/server.py
> Client: Account for edge-case when login token is an empty string

- CHANGES.rst
Just one thing to bring in before cutting a release per GH-580? Apologies for the delay!
> Chore: Update changelog
